spring.application.name=api
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/cgu?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Mysql123*

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

jwt.secret=9a4f2c8d3e1f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0
jwt.expiration=3600000
